Try to split Travis into multiple stages

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -66,83 +66,92 @@ before_install:
       sudo apt-get install -y libsecret-1-dev
     fi
 
-script:
-  - |
-    # Prints some env variables
-    echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
-    echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
-    echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
-    echo "TRAVIS_TAG=$TRAVIS_TAG"
-
-    # Install tools
-    npm install
-
-    # Run test units.
-    # Only do it for pull requests because Travis randomly fails to run them
-    # and that would break the desktop release.
-    if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" = "dev" ]; then
-      npm run test-ci
-      testResult=$?
-      if [ $testResult -ne 0 ]; then
-        exit $testResult
-      fi
-    fi
-
-    # Run Joplin API test units
-    cd Server
-    npm install
-    npm run test
-    testResult=$?
-    if [ $testResult -ne 0 ]; then
-      exit $testResult
-    fi
-    cd ..
-
-    # Run linter for pull requests only - this is so that
-    # bypassing eslint is allowed for urgent fixes.
-    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
-      npm run linter-ci ./
-      testResult=$?
-      if [ $testResult -ne 0 ]; then
-        exit $testResult
-      fi
-    fi
-
-    # Validate translations - this is needed as some users manually
-    # edit .po files (and often make mistakes) instead of using a proper
-    # tool like poedit. Doing it for Linux only is sufficient.
-    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
-      if [ "$TRAVIS_OS_NAME" != "osx" ]; then
-        node packages/tools/validate-translation.js
-        testResult=$?
-        if [ $testResult -ne 0 ]; then
-          exit $testResult
-        fi
-      fi
-    fi
-
-    # Find out if we should run the build or not. Electron-builder gets stuck when
-    # building PRs so we disable it in this case. The Linux build should provide
-    # enough info if the app builds or not.
-    # https://github.com/electron-userland/electron-builder/issues/4263
-    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
-      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
-        exit 0
-      fi
-    fi
-
-    # Prepare the Electron app and build it
-    #
-    # If the current tag is a desktop release tag (starts with "v", such as
-    # "v1.4.7"), we build and publish to github
-    #
-    # Otherwise we only build but don't publish to GitHub. It helps finding
-    # out any issue in pull requests and dev branch.
+jobs:
+  include:
     
-    cd packages/app-desktop
+    - stage: printInfo
+    - script:
+      - |
+        # Prints some env variables
+        echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
+        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
+        echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
+        echo "TRAVIS_TAG=$TRAVIS_TAG"
+    
+    - stage: installDependencies
+    - script:
+      - |
+        # Install tools
+        npm install
 
-    if [[ $TRAVIS_TAG = v* ]]; then
-      USE_HARD_LINKS=false npm run dist
-    else
-      USE_HARD_LINKS=false npm run dist -- --publish=never
-    fi
+    - stage: tests
+    - script:
+      - |
+        # Run test units.
+        # Only do it for pull requests because Travis randomly fails to run them
+        # and that would break the desktop release.
+        if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" = "dev" ]; then
+          npm run test-ci
+          testResult=$?
+          if [ $testResult -ne 0 ]; then
+            exit $testResult
+          fi
+        fi
+
+    - stage: linter
+    - script:
+      - |
+        # Run linter for pull requests only - this is so that
+        # bypassing eslint is allowed for urgent fixes.
+        if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+          npm run linter-ci ./
+          testResult=$?
+          if [ $testResult -ne 0 ]; then
+            exit $testResult
+          fi
+        fi
+
+    - stage: validateTranslations
+    - script:
+      - |
+        # Validate translations - this is needed as some users manually
+        # edit .po files (and often make mistakes) instead of using a proper
+        # tool like poedit. Doing it for Linux only is sufficient.
+        if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+          if [ "$TRAVIS_OS_NAME" != "osx" ]; then
+            node packages/tools/validate-translation.js
+            testResult=$?
+            if [ $testResult -ne 0 ]; then
+              exit $testResult
+            fi
+          fi
+        fi
+
+    - stage: buildAndDeploy
+    - script:
+      - |
+        # Find out if we should run the build or not. Electron-builder gets stuck when
+        # building PRs so we disable it in this case. The Linux build should provide
+        # enough info if the app builds or not.
+        # https://github.com/electron-userland/electron-builder/issues/4263
+        if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
+          if [ "$TRAVIS_OS_NAME" == "osx" ]; then
+            exit 0
+          fi
+        fi
+
+        # Prepare the Electron app and build it
+        #
+        # If the current tag is a desktop release tag (starts with "v", such as
+        # "v1.4.7"), we build and publish to github
+        #
+        # Otherwise we only build but don't publish to GitHub. It helps finding
+        # out any issue in pull requests and dev branch.
+        
+        cd packages/app-desktop
+
+        if [[ $TRAVIS_TAG = v* ]]; then
+          USE_HARD_LINKS=false npm run dist
+        else
+          USE_HARD_LINKS=false npm run dist -- --publish=never
+        fi
