first test on http request for the newly created docker image

diff --git a/.github/workflows/github-actions-main.yml b/.github/workflows/github-actions-main.yml
--- a/.github/workflows/github-actions-main.yml
+++ b/.github/workflows/github-actions-main.yml
@@ -176,3 +176,17 @@ jobs:
           # Basic test to ensure that the created build is valid. It should exit with
           # code 0  if it works.
           docker run joplin/server:0.0.0-beta node dist/app.js migrate list
+      
+      - name: Check HTTP request
+        run: |
+          # Need to pass environment variables:
+          docker run joplin/server:0.0.0-beta node dist/app.js --env dev &
+
+          # Wait for server to start
+          sleep 10
+
+          # Here, check the result - it should be valid json
+          curl http://localhost:22300/api/ping
+
+          # $? returns the last exit code 
+          if [ $? -ne 0 ]; then core.setFailed('Something wrong with the last command'); fi
