handle tests

diff --git a/.github/workflows/github-actions-main.yml b/.github/workflows/github-actions-main.yml
--- a/.github/workflows/github-actions-main.yml
+++ b/.github/workflows/github-actions-main.yml
@@ -1,88 +1,88 @@
 name: Joplin Continuous Integration
 on: [push, pull_request]
 jobs:
-  # Main:
-  #   # We always process server or desktop release tags, because they also publish the release
-  #   if: github.repository == 'laurent22/joplin'
-  #   runs-on: ${{ matrix.os }}
-  #   strategy:
-  #     matrix:
-  #       # Do not use unbuntu-latest because it causes `The operation was canceled` failures:
-  #       # https://github.com/actions/runner-images/issues/6709
-  #       os: [macos-13, ubuntu-22.04, windows-2019]
-  #   steps:
-  #     - uses: actions/checkout@v4
+  Main:
+    # We always process server or desktop release tags, because they also publish the release
+    if: github.repository == 'laurent22/joplin'
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        # Do not use unbuntu-latest because it causes `The operation was canceled` failures:
+        # https://github.com/actions/runner-images/issues/6709
+        os: [macos-13, ubuntu-22.04, windows-2019, ubuntu-22.04-arm]
+    steps:
+      - uses: actions/checkout@v4
 
-  #     - name: Setup build environment
-  #       uses: ./.github/workflows/shared/setup-build-environment
+      - name: Setup build environment
+        uses: ./.github/workflows/shared/setup-build-environment
 
-  #     - name: Install Docker Engine
-  #       # if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/server-v')
-  #       if: runner.os == 'Linux'
-  #       run: |
-  #         sudo apt-get install -y apt-transport-https
-  #         sudo apt-get install -y ca-certificates
-  #         sudo apt-get install -y curl
-  #         sudo apt-get install -y gnupg
-  #         sudo apt-get install -y lsb-release
-  #         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
-  #         echo \
-  #             "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
-  #             $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-  #         sudo apt-get update || true
-  #         sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+      - name: Install Docker Engine
+        # if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/server-v')
+        if: runner.os == 'Linux'
+        run: |
+          sudo apt-get install -y apt-transport-https
+          sudo apt-get install -y ca-certificates
+          sudo apt-get install -y curl
+          sudo apt-get install -y gnupg
+          sudo apt-get install -y lsb-release
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+          echo \
+              "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
+              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+          sudo apt-get update || true
+          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
 
-  #     # Login to Docker only if we're on a server release tag. If we run this on
-  #     # a pull request it will fail because the PR doesn't have access to
-  #     # secrets
-  #     - uses: docker/login-action@v3
-  #       if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/server-v')
-  #       with:
-  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
-  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+      # Login to Docker only if we're on a server release tag. If we run this on
+      # a pull request it will fail because the PR doesn't have access to
+      # secrets
+      - uses: docker/login-action@v3
+        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/server-v')
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-  #     - name: Run tests, build and publish Linux and macOS apps
-  #       if: runner.os == 'Linux' || runner.os == 'macOs'
-  #       env:
-  #         APPLE_ASC_PROVIDER: ${{ secrets.APPLE_ASC_PROVIDER }}
-  #         APPLE_ID: ${{ secrets.APPLE_ID }}
-  #         APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
-  #         APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
-  #         CSC_KEY_PASSWORD: ${{ secrets.APPLE_CSC_KEY_PASSWORD }}
-  #         CSC_LINK: ${{ secrets.APPLE_CSC_LINK }}
-  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
-  #         IS_CONTINUOUS_INTEGRATION: 1
-  #         BUILD_SEQUENCIAL: 1
-  #         SERVER_REPOSITORY: joplin/server
-  #         SERVER_TAG_PREFIX: server
-  #         CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
-  #       run: |
-  #         "${GITHUB_WORKSPACE}/.github/scripts/run_ci.sh"
+      - name: Run tests, build and publish Linux and macOS apps
+        if: runner.os == 'Linux' || runner.os == 'macOs'
+        env:
+          APPLE_ASC_PROVIDER: ${{ secrets.APPLE_ASC_PROVIDER }}
+          APPLE_ID: ${{ secrets.APPLE_ID }}
+          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
+          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
+          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CSC_KEY_PASSWORD }}
+          CSC_LINK: ${{ secrets.APPLE_CSC_LINK }}
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          IS_CONTINUOUS_INTEGRATION: 1
+          BUILD_SEQUENCIAL: 1
+          SERVER_REPOSITORY: joplin/server
+          SERVER_TAG_PREFIX: server
+          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
+        run: |
+          "${GITHUB_WORKSPACE}/.github/scripts/run_ci.sh"
 
-  #     - name: Build and publish Windows app
-  #       if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v')
-  #       env:
-  #         CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_KEY_PASSWORD }}
-  #         CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK }}
-  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
-  #         IS_CONTINUOUS_INTEGRATION: 1
-  #         BUILD_SEQUENCIAL: 1
-  #       # To ensure that the operations stop on failure, all commands
-  #       # should be on one line with "&&" in between.
-  #       run: |
-  #         yarn install && cd packages/app-desktop && yarn dist
+      - name: Build and publish Windows app
+        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v')
+        env:
+          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_KEY_PASSWORD }}
+          CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK }}
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          IS_CONTINUOUS_INTEGRATION: 1
+          BUILD_SEQUENCIAL: 1
+        # To ensure that the operations stop on failure, all commands
+        # should be on one line with "&&" in between.
+        run: |
+          yarn install && cd packages/app-desktop && yarn dist
 
-  #     # Build and package the Windows app, without publishing it, just to
-  #     # verify that the build process hasn't been broken.
-  #     - name: Build Windows app (no publishing)
-  #       if: runner.os == 'Windows' && !startsWith(github.ref, 'refs/tags/v')
-  #       env:
-  #         IS_CONTINUOUS_INTEGRATION: 1
-  #         BUILD_SEQUENCIAL: 1
-  #         SERVER_REPOSITORY: joplin/server
-  #         SERVER_TAG_PREFIX: server
-  #       run: |
-  #         yarn install && cd packages/app-desktop && yarn dist --publish=never
+      # Build and package the Windows app, without publishing it, just to
+      # verify that the build process hasn't been broken.
+      - name: Build Windows app (no publishing)
+        if: runner.os == 'Windows' && !startsWith(github.ref, 'refs/tags/v')
+        env:
+          IS_CONTINUOUS_INTEGRATION: 1
+          BUILD_SEQUENCIAL: 1
+          SERVER_REPOSITORY: joplin/server
+          SERVER_TAG_PREFIX: server
+        run: |
+          yarn install && cd packages/app-desktop && yarn dist --publish=never
 
   ServerDockerImage:
     if: github.repository == 'laurent22/joplin'
@@ -125,7 +125,9 @@ jobs:
           BUILD_SEQUENCIAL: 1
         run: |
           echo "RUNNER_OS=$RUNNER_OS"
+          echo "RUNNER_ARCH=$RUNNER_ARCH"
 
+          # Canvas is only needed for tests and it doesn't build in ARM64 so remove it
           cd packages/lib
           yarn remove canvas
           cd ../..
