Add webapp docker image

diff --git a/.github/workflows/github-actions-main.yml b/.github/workflows/github-actions-main.yml
--- a/.github/workflows/github-actions-main.yml
+++ b/.github/workflows/github-actions-main.yml
@@ -55,6 +55,8 @@ jobs:
           BUILD_SEQUENCIAL: 1
           SERVER_REPOSITORY: joplin/server
           SERVER_TAG_PREFIX: server
+          WEBAPP_REPOSITORY: joplin/webapp
+          WEBAPP_TAG_PREFIX: webapp
           CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
         run: |
           "${GITHUB_WORKSPACE}/.github/scripts/run_ci.sh"
@@ -84,11 +86,20 @@ jobs:
         run: |
           yarn install && cd packages/app-desktop && yarn dist --publish=never
 
-      - name: Publish Docker manifest
+      - name: Publish Docker manifest for server
         if: runner.os == 'Linux'
         env:
           SERVER_REPOSITORY: joplin/server
           SERVER_TAG_PREFIX: server
+        run: |
+          chmod 700 "${GITHUB_WORKSPACE}/.github/scripts/publish_docker_manifest.sh"
+          "${GITHUB_WORKSPACE}/.github/scripts/publish_docker_manifest.sh"
+
+      - name: Publish Docker manifest for webapp
+        if: runner.os == 'Linux'
+        env:
+          WEBAPP_REPOSITORY: joplin/webapp
+          WEBAPP_TAG_PREFIX: webapp
         run: |
           chmod 700 "${GITHUB_WORKSPACE}/.github/scripts/publish_docker_manifest.sh"
           "${GITHUB_WORKSPACE}/.github/scripts/publish_docker_manifest.sh"
@@ -178,3 +189,56 @@ jobs:
             exit 1;
           fi
 
+  WebappDockerImage:
+    if: github.repository == 'laurent22/joplin'
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        # Do not use unbuntu-latest because it causes `The operation was canceled` failures:
+        # https://github.com/actions/runner-images/issues/6709
+        os: [ubuntu-22.04, ubuntu-22.04-arm]
+    steps:
+
+      - name: Install Docker Engine
+        run: |
+          sudo apt-get install -y apt-transport-https
+          sudo apt-get install -y ca-certificates
+          sudo apt-get install -y curl
+          sudo apt-get install -y gnupg
+          sudo apt-get install -y lsb-release
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+          echo \
+              "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
+              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+          sudo apt-get update || true
+          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin
+
+      - uses: actions/checkout@v4
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '18'
+
+      - name: Install Yarn
+        run: |
+          # https://yarnpkg.com/getting-started/install
+          corepack enable
+
+      - name: Build Docker Image
+        env:
+          BUILD_SEQUENCIAL: 1
+        run: |
+          if [ "$RUNNER_ARCH" == "ARM64" ]; then
+            DOCKER_IMAGE_PLATFORM="linux/arm64"
+          fi
+
+          echo "RUNNER_OS=$RUNNER_OS"
+          echo "RUNNER_ARCH=$RUNNER_ARCH"
+          echo "DOCKER_IMAGE_PLATFORM=$DOCKER_IMAGE_PLATFORM"
+
+          yarn install
+          yarn buildWebappDocker --platform $DOCKER_IMAGE_PLATFORM --tag-name webapp-v0.0.0 --repository joplin/webapp
+
+          # Basic test to ensure that the created build is valid. It should exit with
+          # code 0 if it works.
+          docker run joplin/webapp:$(dpkg --print-architecture)-0.0.0 node dist/app.js migrate list
